# Install script for directory: /build/buildd/mysql-5.5-5.5.24

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/usr")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "1")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Info")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/info" TYPE FILE OPTIONAL FILES "/build/buildd/mysql-5.5-5.5.24/Docs/mysql.info")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Info")

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/extra/yassl/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/extra/yassl/taocrypt/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/storage/example/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/storage/csv/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/storage/federated/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/storage/perfschema/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/storage/archive/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/storage/myisam/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/storage/heap/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/storage/myisammrg/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/storage/blackhole/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/storage/innobase/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/plugin/audit_null/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/plugin/daemon_example/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/plugin/semisync/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/plugin/fulltext/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/plugin/auth/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/include/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/dbug/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/strings/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/vio/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/regex/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/mysys/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/libmysql/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/unittest/mytap/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/unittest/mysys/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/extra/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/tests/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/client/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/sql/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/sql/share/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/libservices/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/libmysqld/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/libmysqld/examples/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/mysql-test/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/mysql-test/lib/My/SafeProcess/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/support-files/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/scripts/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/sql-bench/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/man/cmake_install.cmake")
  INCLUDE("/build/buildd/mysql-5.5-5.5.24/builddir/packaging/WiX/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

IF(CMAKE_INSTALL_COMPONENT)
  SET(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
ELSE(CMAKE_INSTALL_COMPONENT)
  SET(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
ENDIF(CMAKE_INSTALL_COMPONENT)

FILE(WRITE "/build/buildd/mysql-5.5-5.5.24/builddir/${CMAKE_INSTALL_MANIFEST}" "")
FOREACH(file ${CMAKE_INSTALL_MANIFEST_FILES})
  FILE(APPEND "/build/buildd/mysql-5.5-5.5.24/builddir/${CMAKE_INSTALL_MANIFEST}" "${file}\n")
ENDFOREACH(file)
